### ISSUE TITLE
Could mark as provide `psr/http-client-implementation`?

### ISSUE THREAD

**Issue by eclipxe13** [sunrise-php/http-client-curl#12]
This package implements contains in `composer.json`:

```json
"provide": {
    "php-http/client-implementation": "1.0"
}
```

Could you please add `"psr/http-client-implementation": "^1.0"` so your package can satisfy this virtual package?

Thanks for your great work!

**Comment by peter279k** [comment]
It looks good if we use the `^1.0` version definition.

Could you create the PR about this?

Thanks.

**Comment by eclipxe13** [comment]
Didn't notice the `^` version constraint in proposal.

Are you sure about it?

In `sunrise/http-factory` you are not using `^`.
Neither for proving `php-http/client-implementation` on this package.

```json
"provide": {
    "psr/http-client-implementation": "^1.0",
    "php-http/client-implementation": "1.0"
}
```
Of course I can make a PR :smile:
